// ── SEED defaults only. Runtime truth lives in store.ts (localStorage CMS). ──
// Edit content via the Admin Dashboard at #/admin — never hardcode new content here.
import type { Programme, StaffMember, ResearchPaper, NewsArticle, DeptEvent, ResourceItem, GalleryItem } from './types.js';

export const PROGRAMMES: Programme[] = [
  { id: 'qs-bsc', title: 'BSc (Hons) Quantity Surveying', unit: 'Quantity Surveying', level: 'Undergraduate', duration: '4 years full-time', summary: 'Cost planning, measurement and digital estimating for resilient delivery.', entryRequirements: ['C+ mean grade with B in Mathematics', 'C+ in English / Kiswahili', 'C in Physics or Chemistry'], modules: ['Measurement I-IV', 'Cost Planning & Control', 'BIM for QS', 'Procurement & Tendering'], careers: ['Quantity Surveyor', 'Estimator', 'Contracts Manager'], badge: 'RICS-aligned' },
  { id: 'qs-msc', title: 'MSc Construction Cost Management', unit: 'Quantity Surveying', level: 'Postgraduate', duration: '2 years part-time', summary: 'Advanced cost modelling and whole-life value for senior commercial roles.', entryRequirements: ['2nd Class Honours in built-environment discipline', 'CV + statement of purpose'], modules: ['Advanced Cost Modelling', 'Risk & Value Engineering', 'Dissertation'], careers: ['Senior Cost Manager', 'Commercial Director'] },
  { id: 'cm-bsc', title: 'BSc Construction Management', unit: 'Construction Management', level: 'Undergraduate', duration: '4 years full-time', summary: 'Site leadership, planning, logistics, safety and lean delivery.', entryRequirements: ['C+ mean grade with C+ in Mathematics', 'C in Physics'], modules: ['Construction Technology', 'Site Safety', 'Project Planning', 'Lean Construction'], careers: ['Site Manager', 'Project Manager', 'Planner'], badge: 'Popular intake' },
  { id: 'cm-dip', title: 'Diploma in Building Construction', unit: 'Construction Management', level: 'Diploma', duration: '2 years + attachment', summary: 'Hands-on route into supervision, setting-out and materials testing.', entryRequirements: ['KCSE C- or artisan certificate', 'Pass in Mathematics'], modules: ['Building Drawing', 'Materials & Workshop', 'Setting Out & Levelling'], careers: ['Site Supervisor', 'Technician'] },
  { id: 'arch-barch', title: 'Bachelor of Architecture (B.Arch)', unit: 'Architecture', level: 'Undergraduate', duration: '5 years + internship', summary: 'Design studio culture, climate-responsive architecture and fabrication.', entryRequirements: ['B plain mean grade', 'B in Maths/Physics and Art/Design', 'Portfolio interview'], modules: ['Design Studio I-X', 'History & Theory', 'Environmental Systems', 'Digital Fabrication'], careers: ['Graduate Architect', 'Urban Designer'], badge: 'Studio flagship' },
  { id: 'arch-march', title: 'Master of Sustainable Architecture', unit: 'Architecture', level: 'Postgraduate', duration: '2 years full-time', summary: 'Net-zero design, passive systems and performance simulation.', entryRequirements: ['B.Arch or related honours degree', 'Design portfolio'], modules: ['Climate-Responsive Design', 'Building Simulation', 'Thesis Project'], careers: ['Sustainability Consultant', 'Design Lead'] },
  { id: 'urp-bsc', title: 'BSc Urban & Regional Planning', unit: 'Urban & Regional Planning', level: 'Undergraduate', duration: '4 years full-time', summary: 'Spatial planning, GIS, transport and housing for liveable cities.', entryRequirements: ['C+ mean grade', 'C+ in Geography/History and Mathematics'], modules: ['Planning Theory', 'GIS & Remote Sensing', 'Transport Planning', 'Planning Studio'], careers: ['Physical Planner', 'GIS Analyst'] },
  { id: 'urp-pgd', title: 'PGDip Urban Resilience', unit: 'Urban & Regional Planning', level: 'Postgraduate', duration: '1 year intensive', summary: 'Flood risk, informality upgrading and data-driven resilience.', entryRequirements: ['Bachelor degree in any field'], modules: ['Urban Risk & Adaptation', 'Upgrading Studio'], careers: ['Resilience Officer', 'County Planner'] },
  { id: 'qs-dip', title: 'Diploma in QS Assistance', unit: 'Quantity Surveying', level: 'Diploma', duration: '2 years', summary: 'Taking-off, BOQ preparation with CAD and Excel workflows.', entryRequirements: ['KCSE C plain', 'C- in Mathematics'], modules: ['Taking-Off', 'BOQ Preparation', 'CAD Essentials'], careers: ['Assistant QS'] },
];
export const STAFF: StaffMember[] = [
  { id: 'hod', name: 'Prof. Amara Njoroge', title: 'Head of Department & Professor', letters: 'PhD, FIQSK, RQS', role: 'Head of Department', type: 'Academic', department: 'Quantity Surveying', specialty: ['Cost Modelling', 'Procurement'], email: 'a.njoroge@university.ac.ke', phone: '+254 700 100 200', bio: 'Prof. Njoroge leads with 20+ years across academia and consultancy. Her whole-life costing research informs procurement policy.', publications: ['Whole-life costing of low-carbon housing (2024)'], photo: '', initials: 'AN' },
  { id: 's2', name: 'Dr. Daniel Otieno', title: 'Senior Lecturer', letters: 'PhD, MAAK', role: 'Coordinator - Architecture', type: 'Academic', department: 'Architecture', specialty: ['Climate Design', 'Vernacular Systems'], email: 'd.otieno@university.ac.ke', phone: '+254 722 310 410', bio: 'Leads design studio and the earthen-architecture lab.', publications: ['Rammed-earth dataset (2023)'], photo: '', initials: 'DO' },
  { id: 's3', name: 'Dr. Faith Wambui', title: 'Lecturer', letters: 'PhD, MISK', role: 'Lecturer - CM', type: 'Academic', department: 'Construction Management', specialty: ['Lean', 'Site Safety'], email: 'f.wambui@university.ac.ke', phone: '+254 733 220 118', bio: 'Former site agent researching lean planning.', publications: ['Last-planner adoption (2024)'], photo: '', initials: 'FW' },
  { id: 's4', name: 'Arch. Kevin Mensah', title: 'Lecturer & Studio Master', letters: 'M.Arch', role: 'Studio Master', type: 'Academic', department: 'Architecture', specialty: ['Fabrication', 'Parametric Design'], email: 'k.mensah@university.ac.ke', phone: '+254 701 555 014', bio: 'Runs the fabrication lab: CNC and clay 3D printing.', publications: ['Parametric screens (2023)'], photo: '', initials: 'KM' },
  { id: 's5', name: 'Dr. Grace Achieng', title: 'Associate Professor', letters: 'PhD', role: 'Research Chair', type: 'Academic', department: 'Urban & Regional Planning', specialty: ['GIS', 'Flood Risk'], email: 'g.achieng@university.ac.ke', phone: '+254 720 884 201', bio: 'Chairs Urban Resilience cluster with county partners.', publications: ['Flood-risk atlas (2024)'], photo: '', initials: 'GA' },
  { id: 's6', name: 'Qs. Peter Kamau', title: 'Assistant Lecturer', letters: 'BSc, Grad QS', role: 'Assistant Lecturer', type: 'Academic', department: 'Quantity Surveying', specialty: ['Measurement', 'BIM 5D'], email: 'p.kamau@university.ac.ke', phone: '+254 715 402 990', bio: 'Teaches measurement and 5D BIM.', publications: [], photo: '', initials: 'PK' },
  { id: 's7', name: 'Ms. Susan Aoko', title: 'Department Administrator', letters: 'MBA', role: 'Administrator', type: 'Administrative', department: 'Dean Office', specialty: ['Admissions', 'Timetabling'], email: 's.aoko@university.ac.ke', phone: '+254 700 100 205', bio: 'First contact for admissions and transcripts.', publications: [], photo: '', initials: 'SA' },
  { id: 's8', name: 'Mr. Brian Kiptoo', title: 'Senior Technologist', letters: 'BTech', role: 'Lab Technologist', type: 'Administrative', department: 'Laboratories', specialty: ['Materials Testing'], email: 'b.kiptoo@university.ac.ke', phone: '+254 700 100 210', bio: 'Custodian of materials and soils labs.', publications: [], photo: '', initials: 'BK' },
];
export const PAPERS: ResearchPaper[] = [
  { id: 'p1', title: 'Low-carbon stabilised earth blocks', authors: ['A. Njoroge', 'D. Otieno'], year: 2024, cluster: 'Sustainable Materials', abstract: '240 mixes tested; 30% cement cut at 3.5 MPa, 22% cheaper.', journal: 'J. Sustainable Construction', doi: '10.0000/be.2024.001', downloads: 1842 },
  { id: 'p2', title: 'Digital twins for mid-rise logistics', authors: ['F. Wambui', 'K. Mensah'], year: 2024, cluster: 'Smart Infrastructure', abstract: 'BIM+IoT twin cut crane idle 18% on live sites.', journal: 'Automation in Construction', doi: '10.0000/be.2024.002', downloads: 1204 },
  { id: 'p3', title: 'Flood exposure mapping with open EO data', authors: ['G. Achieng et al.'], year: 2024, cluster: 'Urban Resilience', abstract: 'Sentinel + community mapping adopted by 2 counties.', journal: 'Habitat Innovation', doi: '10.0000/be.2024.003', downloads: 2310 },
  { id: 'p4', title: 'Bamboo-composite roof trusses', authors: ['D. Otieno', 'P. Kamau'], year: 2023, cluster: 'Sustainable Materials', abstract: '6m spans at half timber cost.', journal: 'Construction & Bio-materials', doi: '10.0000/be.2023.004', downloads: 987 },
  { id: 'p5', title: 'Sensor-guided concrete curing', authors: ['B. Kiptoo', 'F. Wambui'], year: 2023, cluster: 'Smart Infrastructure', abstract: 'Maturity sensors, zero premature striking.', journal: 'Materials & Methods', doi: '10.0000/be.2023.005', downloads: 764 },
  { id: 'p6', title: 'Upgrading without displacement', authors: ['G. Achieng'], year: 2021, cluster: 'Urban Resilience', abstract: 'Tenure-sensitive participation protocol.', journal: 'Planning Practice', doi: '10.0000/be.2021.006', downloads: 1530 },
];
export const NEWS: NewsArticle[] = [
  { id: 'n1', title: 'Class of 2026 wins National BIM Challenge', date: '12 Sep 2026', category: 'Student Success', summary: '5D-BIM team beat 14 universities with net-zero hostel.', body: ['Modelled 400-bed hostel in Revit and CostX.', 'First whole-life carbon ledger in contest history.'] },
  { id: 'n2', title: 'New Materials & Structures Lab opens', date: '28 Aug 2026', category: 'Facilities', summary: '600 sqm lab doubles final-year capacity.', body: ['200T press, curing chambers, soils wing.', 'Evening slots bookable via Resources hub.'] },
  { id: 'n3', title: 'Department signs county resilience pact', date: '09 Aug 2026', category: 'Partnerships', summary: 'Three counties co-fund flood studios.', body: ['County co-crits each semester.', '10 sponsored dissertations open October.'] },
];
export const EVENTS: DeptEvent[] = [
  { id: 'e1', title: 'Open Day & Studio Exhibition', date: 'Sat 18 Oct 2026', time: '09:00-16:00', location: 'Built Environment Complex, Atrium', tag: 'Admissions', description: 'Tours, portfolio clinics for B.Arch.' },
  { id: 'e2', title: 'Construction Innovation Symposium', date: 'Thu 06 Nov 2026', time: '08:30-17:00', location: 'Main Auditorium', tag: 'Research', description: 'Digital twins, earthen construction. CPD points.' },
  { id: 'e3', title: 'Site Safety Week & Crane Demo', date: 'Mon 17 Nov 2026', time: '10:00-13:00', location: 'Site Yard B', tag: 'Workshop', description: 'Harness and lifting clinics. PPE provided.' },
  { id: 'e4', title: 'Postgraduate Colloquium', date: 'Fri 05 Dec 2026', time: '14:00-17:30', location: 'Seminar Room 3', tag: 'Postgraduate', description: 'Mid-thesis presentations.' },
];
export const RESOURCES: ResourceItem[] = [
  { id: 'r1', title: 'Semester Timetable (Sep-Dec 2026)', category: 'Timetable', meta: 'PDF - 8 pages', description: 'Lecture rooms, studios and labs.', fileName: 'timetable-2026.pdf', fileKind: 'PDF' },
  { id: 'r2', title: 'Lab Booking Schedule', category: 'Timetable', meta: 'PDF - evening slots', description: 'Fabrication and materials labs.', fileName: 'lab-schedule.pdf', fileKind: 'PDF' },
  { id: 'r3', title: 'County Attachment Call', category: 'Notices', meta: 'Deadline 24 Oct', description: '30 sponsored Year-3 places.', fileName: 'attachment-call.pdf', fileKind: 'Notice' },
  { id: 'r4', title: 'Dissertation Guidelines', category: 'Notices', meta: 'Turnitin + binding', description: 'Formatting and defence rules.', fileName: 'dissertation-guide.pdf', fileKind: 'Guide' },
  { id: 'r5', title: 'Graduate Trainee - Cost (2 posts)', category: 'Internship', meta: 'Paid - 31 Oct', description: '5D-BIM rotation to RQS.', fileName: 'trainee-cost.pdf', fileKind: 'Role' },
  { id: 'r6', title: 'Site Intern - Tier-1 (6 posts)', category: 'Internship', meta: 'Stipend + PPE', description: 'Live frame QA experience.', fileName: 'site-intern.pdf', fileKind: 'Role' },
  { id: 'r7', title: 'QS Handbook', category: 'Handbook', meta: '48 pages', description: 'Structure and assessment rules.', fileName: 'qs-handbook.pdf', fileKind: 'Handbook' },
  { id: 'r8', title: 'B.Arch Studio Guide', category: 'Handbook', meta: '36 pages', description: 'Portfolio and review criteria.', fileName: 'barch-guide.pdf', fileKind: 'Handbook' },
];
export const GALLERY: GalleryItem[] = [
  { id: 'g1', title: 'Atrium Crit Day', category: 'Campus', caption: 'Pin-up in the atrium.', gradient: 'linear-gradient(135deg,#1b3b36,#2f6b5e)', emoji: '🏛️' },
  { id: 'g2', title: 'Materials Lab', category: 'Labs', caption: 'Block crushing series.', gradient: 'linear-gradient(135deg,#7c2d12,#d97706)', emoji: '🧱' },
  { id: 'g3', title: 'Survey Camp', category: 'Field Trips', caption: 'Year 2 traverse.', gradient: 'linear-gradient(135deg,#0c4a6e,#0284c7)', emoji: '📐' },
  { id: 'g4', title: 'Bamboo Truss', category: 'Student Projects', caption: '6m prototype.', gradient: 'linear-gradient(135deg,#3f6212,#65a30d)', emoji: '🎋' },
  { id: 'g5', title: 'CNC Mill', category: 'Labs', caption: 'Parametric screens.', gradient: 'linear-gradient(135deg,#312e81,#7c3aed)', emoji: '⚙️' },
  { id: 'g6', title: 'Mapping Studio', category: 'Field Trips', caption: 'Flood-walk with officers.', gradient: 'linear-gradient(135deg,#0f766e,#14b8a6)', emoji: '🗺️' },
  { id: 'g7', title: 'Net-Zero Model', category: 'Student Projects', caption: 'BIM winning entry.', gradient: 'linear-gradient(135deg,#92400e,#f59e0b)', emoji: '🏠' },
  { id: 'g8', title: 'Reading Terrace', category: 'Campus', caption: 'Collection floor.', gradient: 'linear-gradient(135deg,#1e293b,#475569)', emoji: '📚' },
];

